// US city list for the funnel city autocomplete (City, ST). Major metros +
// common medspa markets. Edit freely — the autocomplete matches on substring.
window.NB_CITIES = [
  "New York, NY","Los Angeles, CA","Chicago, IL","Houston, TX","Phoenix, AZ",
  "Philadelphia, PA","San Antonio, TX","San Diego, CA","Dallas, TX","San Jose, CA",
  "Austin, TX","Jacksonville, FL","Fort Worth, TX","Columbus, OH","Charlotte, NC",
  "San Francisco, CA","Indianapolis, IN","Seattle, WA","Denver, CO","Washington, DC",
  "Boston, MA","El Paso, TX","Nashville, TN","Detroit, MI","Oklahoma City, OK",
  "Portland, OR","Las Vegas, NV","Memphis, TN","Louisville, KY","Baltimore, MD",
  "Milwaukee, WI","Albuquerque, NM","Tucson, AZ","Fresno, CA","Sacramento, CA",
  "Kansas City, MO","Mesa, AZ","Atlanta, GA","Omaha, NE","Colorado Springs, CO",
  "Raleigh, NC","Long Beach, CA","Virginia Beach, VA","Miami, FL","Oakland, CA",
  "Minneapolis, MN","Tulsa, OK","Bakersfield, CA","Wichita, KS","Arlington, TX",
  "Aurora, CO","Tampa, FL","New Orleans, LA","Cleveland, OH","Honolulu, HI",
  "Anaheim, CA","Lexington, KY","Stockton, CA","Corpus Christi, TX","Henderson, NV",
  "Riverside, CA","Newark, NJ","Saint Paul, MN","Santa Ana, CA","Cincinnati, OH",
  "Irvine, CA","Orlando, FL","Pittsburgh, PA","St. Louis, MO","Greensboro, NC",
  "Jersey City, NJ","Anchorage, AK","Lincoln, NE","Plano, TX","Durham, NC",
  "Buffalo, NY","Chandler, AZ","Chula Vista, CA","Toledo, OH","Madison, WI",
  "Gilbert, AZ","Reno, NV","Fort Wayne, IN","North Las Vegas, NV","St. Petersburg, FL",
  "Lubbock, TX","Irving, TX","Laredo, TX","Winston-Salem, NC","Chesapeake, VA",
  "Glendale, AZ","Garland, TX","Scottsdale, AZ","Norfolk, VA","Boise, ID",
  "Fremont, CA","Spokane, WA","Santa Clarita, CA","Baton Rouge, LA","Richmond, VA",
  "Hialeah, FL","San Bernardino, CA","Tacoma, WA","Modesto, CA","Huntsville, AL",
  "Des Moines, IA","Yonkers, NY","Rochester, NY","Moreno Valley, CA","Fayetteville, NC",
  "Fontana, CA","Columbus, GA","Worcester, MA","Port St. Lucie, FL","Little Rock, AR",
  "Augusta, GA","Oxnard, CA","Birmingham, AL","Montgomery, AL","Frisco, TX",
  "Amarillo, TX","Salt Lake City, UT","Grand Rapids, MI","Huntington Beach, CA","Overland Park, KS",
  "Glendale, CA","Tallahassee, FL","Grand Prairie, TX","McKinney, TX","Cape Coral, FL",
  "Sioux Falls, SD","Peoria, AZ","Providence, RI","Vancouver, WA","Knoxville, TN",
  "Akron, OH","Shreveport, LA","Mobile, AL","Brownsville, TX","Newport News, VA",
  "Fort Lauderdale, FL","Chattanooga, TN","Tempe, AZ","Aurora, IL","Elk Grove, CA",
  "Ontario, CA","Salem, OR","Cary, NC","Santa Rosa, CA","Rancho Cucamonga, CA",
  "Eugene, OR","Oceanside, CA","Clarksville, TN","Garden Grove, CA","Lancaster, CA",
  "Springfield, MO","Pembroke Pines, FL","Fort Collins, CO","Palmdale, CA","Salinas, CA",
  "Hayward, CA","Corona, CA","Paterson, NJ","Murfreesboro, TN","Macon, GA",
  "Lakewood, CO","Killeen, TX","Springfield, MA","Alexandria, VA","Kansas City, KS",
  "Sunnyvale, CA","Hollywood, FL","Roseville, CA","Charleston, SC","Escondido, CA",
  "Joliet, IL","Jackson, MS","Bellevue, WA","Surprise, AZ","Naperville, IL",
  "Pasadena, TX","Pomona, CA","Bridgeport, CT","Denton, TX","Rockford, IL",
  "Mesquite, TX","Savannah, GA","Syracuse, NY","McAllen, TX","Torrance, CA",
  "Olathe, KS","Visalia, CA","Thornton, CO","Fullerton, CA","Gainesville, FL",
  "West Palm Beach, FL","Orange, CA","Warren, MI","Hampton, VA","Dayton, OH",
  "Columbia, SC","Pasadena, CA","Stamford, CT","Victorville, CA","Elizabeth, NJ",
  "Miramar, FL","Coral Springs, FL","Carrollton, TX","Midland, TX","Waco, TX",
  "Round Rock, TX","Sterling Heights, MI","Kent, WA","Norman, OK","Santa Clara, CA",
  "Abilene, TX","Athens, GA","Columbia, MO","Thousand Oaks, CA","Vallejo, CA",
  "Wilmington, NC","Concord, CA","Topeka, KS","Simi Valley, CA","Hartford, CT",
  "Charleston, WV","Evansville, IN","Fargo, ND","Billings, MT","Boca Raton, FL",
  "Naples, FL","Sarasota, FL","Scranton, PA","Allentown, PA","Greenville, SC",
  "Nashua, NH","Boulder, CO","Bend, OR","Asheville, NC","Savannah, GA"
];
